apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-private-read-run- # make name automate with random index ( for re use pipelinerun yaml )
spec:
  serviceAccountName: tekton-sa # sa for git credientials -> pipeline will use for clone private repo
  pipelineRef: # select pipeline
    name: clone-private-read
  podTemplate: # setting taskpod
    securityContext:  # pod security
      fsGroup: 65532 # set volume owner gid = 65532
  workspaces: # volume for clone code
  - name: shared-private-data
    volumeClaimTemplate: # automatically create pvc -> create pv
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-credential-basic
    secret:
      secretName: git-credential-basic
  params: # git address
  - name: repo-url
    # value: "https://github.com/lijahong/tektontest"
    value: "https://github.com/oebinu/sample-python.git"
    # value: "https://git@github.com:oebinu/sample-python.git"