apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tekton-deploy- # make name automate with random index ( for re use pipelinerun yaml )
spec:
  serviceAccountName: tekton-build # sa for git credientials -> pipeline will use for clone private repo
  pipelineRef: # select pipeline
    name: tekton-deploy
  podTemplate: # setting taskpod
    securityContext:  # pod security
      fsGroup: 65532 # set volume owner gid = 65532
  workspaces: # volume for clone code
  - name: shared-data
    volumeClaimTemplate: # automatically create pvc -> create pv
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

  params: # git address
  - name: repo-url
    value: "https://github.com/oebinu/tekton-sample.git"
  - name: image-reference
    value: cocopopo/tekton-sample:v2
  - name: kubectl-args
    value:
      - "ls -la"
      # - "apply"
      # - "-f"
      # - "10_k8s_deploy.yaml"s