apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tekton-sample-deploy
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: tekton
  template: 
    metadata: 
      name: tekton-sample-deploy
      labels: 
        app: tekton
    spec:
      containers: 
      - name: tekton
        image: cocopopo/tekton-sample:v2
        ports:
        - containerPort: 80
      ### 아래를 추가한다
      imagePullSecrets:
      - name: docker-credentials

      
---

apiVersion: v1
kind: Service
metadata:
  name: tekton-sample-deploy
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: tekton